# Generated by Django 5.2.9 on 2026-07-03 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0127_alter_item_source_add_storyteller"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Instrument/role, e.g. 'guitar', 'vocals'",
                        max_length=255,
                    ),
                ),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("left_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_current", "member__name"],
            },
        ),
        migrations.AddField(
            model_name="artist",
            name="artist_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MusicBrainz artist type, e.g. 'Group' or 'Person'",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="members_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When band members were last synced from MusicBrainz",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="artistmember",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="app.artist",
            ),
        ),
        migrations.AddField(
            model_name="artistmember",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bands",
                to="app.artist",
            ),
        ),
        migrations.AddConstraint(
            model_name="artistmember",
            constraint=models.UniqueConstraint(
                fields=("band", "member", "role"), name="unique_artist_member_role"
            ),
        ),
    ]
