# Generated by Django 5.2.9 on 2026-07-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0128_artistmember_remove_item_app_item_source_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovertasteprofile",
            name="world_alignment_offsets",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="world_alignment_offset_samples",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="avoidance_offsets",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="avoidance_baselines",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="discovertasteprofile",
            name="profile_schema_version",
            field=models.IntegerField(default=1),
        ),
    ]
