# Generated by Django 5.2.9 on 2026-07-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0131_discover_taste_profile_genre_primacy_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="igdb_user_rating",
            field=models.FloatField(
                blank=True,
                help_text="Pure user rating value from IGDB metadata",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="igdb_user_rating_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="User rating count from IGDB metadata", null=True
            ),
        ),
    ]
