# Generated by Django 5.2.9 on 2026-07-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0132_item_igdb_user_rating_item_igdb_user_rating_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                    ("discover", "Discover Metadata"),
                    ("game_lengths", "Game Lengths"),
                    ("trakt_popularity", "Trakt Popularity"),
                    ("igdb_ratings", "IGDB Ratings"),
                ],
                max_length=20,
            ),
        ),
    ]
