# Generated by Django 5.2.10 on 2026-07-16

from django.db import migrations, models


def backfill_episode_status(apps, schema_editor):
    Episode = apps.get_model("app", "Episode")
    Episode.objects.filter(dropped=True).update(status="Dropped")
    Episode.objects.filter(dropped=False, end_date__isnull=True).update(
        status="In progress",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0134_item_app_item_media_lookup_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="episode",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_episode_status, migrations.RunPython.noop),
    ]
