# Generated by Django 5.2.16 on 2026-07-20 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0135_episode_tracking_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "TV Show"),
                            ("season", "TV Season"),
                            ("episode", "Episode"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("game", "Game"),
                            ("book", "Book"),
                            ("comic", "Comic"),
                            ("comicissue", "Comic Issue"),
                            ("boardgame", "Board Game"),
                            ("music", "Music"),
                            ("podcast", "Podcast"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("tvdb", "TheTVDB"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("imdb", "IMDb"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("bgg", "BoardGameGeek"),
                            ("musicbrainz", "MusicBrainz"),
                            ("pocketcasts", "Pocket Casts"),
                            ("gpodder", "GPodder"),
                            ("audiobookshelf", "Audiobookshelf"),
                            ("storyteller", "Storyteller"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("media_id", models.CharField(max_length=20)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "media_type", "source", "media_id"),
                        name="deletedmedia_unique_user_media_type_source_media_id",
                    )
                ],
            },
        ),
    ]
