# Generated by Django 5.2.16 on 2026-07-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0136_deletedmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalepisode",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
