# Generated by Django 5.2.16 on 2026-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0137_historicalepisode_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="local_season_episode_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Authoritative episode count for a season the provider is missing, sourced from the media server so progress can still complete",
                null=True,
            ),
        ),
    ]
