# Generated by Django 5.2.16 on 2026-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0138_item_local_season_episode_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="metadata_migration_pinned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When automatic metadata-provider migration (e.g. TMDB->TVDB) was skipped for this item due to an incompatible season/episode structure, so future runs don't keep retrying it",
                null=True,
            ),
        ),
    ]
