# Generated by Django 5.2.16 on 2026-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0139_item_metadata_migration_pinned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionentry",
            name="purchase_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Where the item was purchased or which service/retailer it's tied to",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Purchase price",
                max_digits=10,
                null=True,
            ),
        ),
    ]
