# Generated by Django 5.2.16 on 2026-08-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0141_alter_anime_status_alter_basicmedia_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpodcast",
            name="position_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When played_up_to_seconds last changed. Media.progressed_at only monitors 'progress', so the playback progress API needs its own timestamp for ?updated_since= delta sync.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="position_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When played_up_to_seconds last changed. Media.progressed_at only monitors 'progress', so the playback progress API needs its own timestamp for ?updated_since= delta sync.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PlaybackProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_seconds", models.PositiveIntegerField()),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_progress",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Playback progress",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="app_playbac_user_id_342e90_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"),
                        name="playbackprogress_unique_user_item",
                    )
                ],
            },
        ),
    ]
