# Generated by Django 5.2.16 on 2026-08-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0144_item_watch_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatabackfillstate",
            name="field",
            field=models.CharField(
                choices=[
                    ("runtime", "Runtime"),
                    ("genres", "Genres"),
                    ("credits", "Credits"),
                    ("release", "Release Date"),
                    ("discover", "Discover Metadata"),
                    ("game_lengths", "Game Lengths"),
                    ("trakt_popularity", "Trakt Popularity"),
                    ("igdb_ratings", "IGDB Ratings"),
                    ("watch_providers", "Watch Providers"),
                ],
                max_length=20,
            ),
        ),
    ]
