# Generated by Django 5.2.16 on 2026-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0145_alter_metadatabackfillstate_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackfillReconcileState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("strategy_version", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_after", models.DateTimeField(blank=True, null=True)),
                ("consecutive_no_op_runs", models.PositiveIntegerField(default=0)),
                ("last_cursor_item_id", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "strategy_version"],
                        name="app_backfil_key_ac747a_idx",
                    )
                ],
            },
        ),
    ]
