# Generated by Django 5.2.16 on 2026-08-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_backfill_reconcile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calendar_checked_at',
            field=models.DateTimeField(blank=True, help_text='When calendar releases were last fetched for this item', null=True),
        ),
    ]
