# Generated by Django 5.2.16 on 2026-08-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0147_item_calendar_checked_at"),
        ("app", "0148_merge_duplicate_item_buckets"),
    ]

    operations = []
