# Generated by Django 5.2.16 on 2026-08-10 03:33

import django.db.models.deletion
from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0150_item_synopsis"),
        ("integrations", "0021_importrun"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="anime",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="basicmedia",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="boardgame",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="book",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="comic",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="comicissue",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="game",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalanime",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalbasicmedia",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalboardgame",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalbook",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalcomic",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalcomicissue",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalgame",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalmanga",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalmovie",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalmusic",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalpodcast",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicalseason",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="historicaltv",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="manga",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="movie",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="music",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="podcast",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="season",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
        AddFieldIfNotExists(
            model_name="tv",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The import run that created or last touched this row, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="integrations.importrun",
            ),
        ),
    ]
