# Generated by Django 5.2.16 on 2026-08-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0151_anime_import_run_basicmedia_import_run_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoviePlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="app.movie",
                    ),
                ),
            ],
            options={
                "ordering": ["movie", "-end_date", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("external_id__isnull", False),
                            models.Q(("external_id", ""), _negated=True),
                        ),
                        fields=("movie", "external_id"),
                        name="app_movieplay_unique_movie_external_id",
                    )
                ],
            },
        ),
    ]
