# Generated by Django 5.2.16 on 2026-08-17

from django.conf import settings
from django.db import migrations

# The placeholder previously hotlinked TMDB's glyphicons SVG. Existing rows
# stored that URL in their image column. Rewrite them to the current embedded
# data-URI placeholder so they are recognised as "no image" again.
OLD_IMG_NONE = (
    "https://www.themoviedb.org/assets/2/v4/glyphicons/basic/"
    "glyphicons-basic-38-picture-grey-c2ebdbb057f2a7614185931650f8cee23fa137b93812ccb132b9df511df1cfac.svg"
)


def rewrite_old_placeholder(apps, schema_editor):
    new_value = settings.IMG_NONE
    if new_value == OLD_IMG_NONE:
        return

    for model_name in ("Item", "Person", "Artist", "Album", "PodcastShow"):
        model = apps.get_model("app", model_name)
        model.objects.filter(image=OLD_IMG_NONE).update(image=new_value)


def reverse_placeholder(apps, schema_editor):
    # No-op: we don't restore the old hotlink on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0154_episode_watch_operation_id"),
    ]

    operations = [
        migrations.RunPython(rewrite_old_placeholder, reverse_placeholder),
    ]
