# Generated by Django 5.2.16 on 2026-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0154_episode_watch_operation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=64, unique=True)),
                ("source", models.CharField(max_length=20)),
                ("media_type", models.CharField(max_length=32)),
                ("media_id", models.CharField(max_length=500)),
                ("language", models.CharField(blank=True, default="", max_length=35)),
                ("season_numbers", models.JSONField(blank=True, default=list)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                ("edition_id", models.CharField(blank=True, default="", max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("payload_hash", models.CharField(blank=True, default="", max_length=64)),
                ("payload_size", models.PositiveIntegerField(default=0)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("local", "Local"),
                            ("refreshing", "Refreshing"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="local",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("provider", "Provider"),
                            ("item", "Item"),
                            ("import", "Import"),
                            ("api", "API"),
                            ("refresh", "Refresh"),
                            ("manual", "Manual"),
                        ],
                        default="item",
                        max_length=16,
                    ),
                ),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("refresh_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, default="", max_length=80)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source", "media_type", "media_id", "cache_key"],
                "indexes": [
                    models.Index(
                        fields=["source", "media_type", "media_id"],
                        name="app_meta_snap_lookup_idx",
                    ),
                    models.Index(
                        fields=["state", "last_attempted_at"],
                        name="app_meta_snap_state_idx",
                    ),
                    models.Index(
                        fields=["fetched_at"],
                        name="app_meta_snap_fetched_idx",
                    ),
                ],
            },
        ),
    ]
