# Generated by Django 5.2.16 on 2026-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_rewrite_old_img_none_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='podcastshow',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
