# Generated by Django 5.2.16 on 2026-09-06 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0176_move_hardcover_user_key"),
        ("integrations", "0036_merge_20260905_1122"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionEntrySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Importer that produced the copy, e.g. 'clz'",
                        max_length=32,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(
                        help_text="Stable record id from the source, or a derived identity",
                        max_length=200,
                    ),
                ),
                (
                    "occurrence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Index among rows sharing a source_record_id in one export",
                    ),
                ),
                (
                    "derived_identity",
                    models.BooleanField(
                        default=False,
                        help_text="Whether source_record_id was derived rather than supplied",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="integrations.importrun",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_records",
                        to="app.collectionentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_entry_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "source"], name="app_collect_user_id_308e72_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source", "source_record_id", "occurrence"),
                        name="app_collectionentrysource_unique_user_record",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionFieldSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Importer that produced the column, e.g. 'clz' or 'yamtrack'",
                        max_length=32,
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        help_text="Normalized column key as it appears in the source export",
                        max_length=200,
                    ),
                ),
                (
                    "source_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original column label, preserved verbatim for provenance",
                        max_length=200,
                    ),
                ),
                (
                    "created_field",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this import created the field rather than reusing one",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="integrations.importrun",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_mappings",
                        to="app.collectionfield",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_field_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "source"], name="app_collect_user_id_abc9d8_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source", "source_key"),
                        name="app_collectionfieldsource_unique_user_source_key",
                    )
                ],
            },
        ),
    ]
