# Generated by Django 5.2.16 on 2026-09-07 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0177_collectionentrysource_collectionfieldsource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchStateSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_sequence", models.BigIntegerField(default=0)),
                ("emit_changes", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_state_sequence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="WatchState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.BooleanField(default=False)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("first_watched_at", models.DateTimeField(blank=True, null=True)),
                ("last_watched_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("sequence", models.BigIntegerField(default=0)),
                (
                    "state_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "origin_kind",
                    models.CharField(
                        choices=[
                            ("local_ui", "Local UI"),
                            ("local_api", "Local API"),
                            ("webhook", "Provider webhook"),
                            ("provider_pull", "Provider pull"),
                            ("import", "Import"),
                            ("backfill", "Backfill"),
                            ("reconcile", "Reconciliation"),
                        ],
                        default="backfill",
                        max_length=24,
                    ),
                ),
                (
                    "origin_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("conflicted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_states",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="app_watchst_user_id_b773df_idx",
                    ),
                    models.Index(
                        fields=["user", "sequence"],
                        name="app_watchst_user_id_84617c_idx",
                    ),
                    models.Index(
                        fields=["item"], name="app_watchst_item_id_b976ad_idx"
                    ),
                    models.Index(
                        condition=models.Q(("conflicted", True)),
                        fields=["user"],
                        name="app_watchstate_conflicted",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"), name="app_watchstate_unique_user_item"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchStateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.BigIntegerField()),
                ("revision", models.PositiveIntegerField()),
                (
                    "previous_revision",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("upsert", "Upsert"), ("delete", "Delete")],
                        default="upsert",
                        max_length=8,
                    ),
                ),
                ("watched", models.BooleanField(blank=True, null=True)),
                ("play_count", models.PositiveIntegerField(blank=True, null=True)),
                ("watched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "origin_kind",
                    models.CharField(
                        choices=[
                            ("local_ui", "Local UI"),
                            ("local_api", "Local API"),
                            ("webhook", "Provider webhook"),
                            ("provider_pull", "Provider pull"),
                            ("import", "Import"),
                            ("backfill", "Backfill"),
                            ("reconcile", "Reconciliation"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "origin_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "origin_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("origin_observed_at", models.DateTimeField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("causation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watch_state_changes",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_state_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["user", "item", "-sequence"],
                        name="app_watchst_user_id_3d388f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "sequence"),
                        name="app_watchstatechange_unique_user_sequence",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("origin_event_id__isnull", False)),
                        fields=("user", "origin_key", "origin_event_id"),
                        name="app_watchstatechange_unique_origin_event",
                    ),
                ],
            },
        ),
    ]
