# Generated by Django 5.2.16 on 2026-09-19 17:41

from django.db import migrations, models


def column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        columns = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    return any(column.name == column_name for column in columns)


class AddFieldIfNotExists(migrations.AddField):
    """Preserve state while tolerating a column already present in a fork."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        if column_exists(schema_editor, model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0186_episode_external_id'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='applicationsettings',
            name='public_branding',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
