# Generated by Django 5.2.16 on 2026-09-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0193_add_gcd_source"),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmusic',
            name='origin_url',
            field=models.CharField(blank=True, default='', help_text='Client origin URL for this play, when the scrobble sent one.', max_length=500),
        ),
        migrations.AddField(
            model_name='music',
            name='origin_url',
            field=models.CharField(blank=True, default='', help_text='Client origin URL for this play, when the scrobble sent one.', max_length=500),
        ),
    ]
