# Generated by Django 5.2.9 on 2026-07-12 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0015_storytelleraccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MDBListAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.TextField(help_text="Encrypted MDBList API key")),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("6h", "Every 6 hours"),
                            ("12h", "Every 12 hours"),
                            ("24h", "Every 24 hours"),
                            ("weekly", "Weekly"),
                        ],
                        default="24h",
                        max_length=10,
                    ),
                ),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mdblist_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MDBList account",
                "verbose_name_plural": "MDBList accounts",
            },
        ),
    ]
