# Generated by Django 5.2.9 on 2026-07-12 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0016_mdblistaccount"),
        ("integrations", "0016_stremioaccount"),
    ]

    operations = []
