# Generated by Django 5.2.9 on 2026-07-16 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0017_merge_0016_mdblistaccount_0016_stremioaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JellyfinAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(help_text="Jellyfin server URL")),
                ("api_key", models.TextField(help_text="Encrypted Jellyfin API key")),
                (
                    "jellyfin_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "jellyfin_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "push_watched_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Push Yamtrack 'watched' status to Jellyfin",
                    ),
                ),
                (
                    "push_unwatched_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Push Yamtrack 'unwatched' status to Jellyfin",
                    ),
                ),
                (
                    "scheduled_push_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Push watched state to Jellyfin on a recurring schedule",
                    ),
                ),
                (
                    "instant_push_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Push watched state to Jellyfin right after a webhook event",
                    ),
                ),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jellyfin_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jellyfin account",
                "verbose_name_plural": "Jellyfin accounts",
            },
        ),
    ]
