# Generated by Django 5.2.16 on 2026-07-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0018_jellyfinaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobookshelfaccount",
            name="create_missing",
            field=models.BooleanField(
                default=True,
                help_text="Create Floppy items when ABS items cannot be matched",
            ),
        ),
        migrations.AlterField(
            model_name="gpodderaccount",
            name="device_id",
            field=models.CharField(
                help_text="Floppy-managed GPodder device identifier", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="jellyfinaccount",
            name="push_unwatched_enabled",
            field=models.BooleanField(
                default=False, help_text="Push Floppy 'unwatched' status to Jellyfin"
            ),
        ),
        migrations.AlterField(
            model_name="jellyfinaccount",
            name="push_watched_enabled",
            field=models.BooleanField(
                default=True, help_text="Push Floppy 'watched' status to Jellyfin"
            ),
        ),
    ]
