# Generated by Django 5.2.16 on 2026-08-01 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0019_rename_yamtrack_help_text_to_floppy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KoitoAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(help_text="Koito server URL")),
                ("api_key", models.TextField(help_text="Encrypted Koito API key")),
                (
                    "last_fetch_timestamp_uts",
                    models.IntegerField(
                        blank=True,
                        help_text="Unix timestamp (seconds) of last successful poll",
                        null=True,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_broken",
                    models.BooleanField(
                        default=False,
                        help_text="True if connection is broken (invalid key or persistent errors)",
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive failures"
                    ),
                ),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "history_import_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        default="idle",
                        help_text="Current Koito history import state",
                        max_length=20,
                    ),
                ),
                (
                    "history_import_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "history_import_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "history_import_last_error_message",
                    models.TextField(blank=True, default=""),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koito_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Koito account",
                "verbose_name_plural": "Koito accounts",
            },
        ),
    ]
