# Generated by Django 5.2.16 on 2026-08-05 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0021_importrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XboxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(help_text='Encrypted OpenXBL API key')),
                ('xuid', models.CharField(blank=True, default='', max_length=32)),
                ('gamertag', models.CharField(blank=True, default='', max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xbox_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xbox account',
                'verbose_name_plural': 'Xbox accounts',
            },
        ),
    ]
