# Generated by Django 5.2.16 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0022_xboxaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlexWebhookShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plex_username", models.CharField(max_length=255)),
                (
                    "allowed_libraries",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text=(
                            "Plex library keys accepted for this share; "
                            "null means all libraries."
                        ),
                        null=True,
                    ),
                ),
                (
                    "recipient_enabled",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Whether the recipient has opted into this shared webhook."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plex_webhook_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_plex_webhook_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plex webhook share",
                "verbose_name_plural": "Plex webhook shares",
                "indexes": [
                    models.Index(
                        fields=["owner", "recipient_enabled"],
                        name="plexshare_owner_enabled_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "recipient"),
                        name="integrations_plexwebhookshare_unique_owner_recipient",
                    ),
                ],
            },
        ),
    ]
