# Generated by Django 5.2.16 on 2026-08-15 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_integrationeventreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSNAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npsso', models.TextField(help_text='Encrypted PSN NPSSO token')),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('online_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psn_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlayStation Network account',
                'verbose_name_plural': 'PlayStation Network accounts',
            },
        ),
    ]
