# Generated by Django 5.2.16 on 2026-09-25 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0047_merge_20260910_1141"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionsourcestate",
            name="source",
            field=models.CharField(
                choices=[
                    ("plex", "Plex"),
                    ("jellyfin", "Jellyfin"),
                    ("radarr", "Radarr"),
                    ("sonarr", "Sonarr"),
                    ("mylar", "Mylar3"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="collectionsourcestate",
            name="source_instance_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="PK of the Radarr/Sonarr/Mylar instance this row came from; unused for plex/jellyfin",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MylarInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label to distinguish multiple instances",
                        max_length=100,
                    ),
                ),
                ("base_url", models.URLField(help_text="Mylar3 server URL")),
                ("api_key", models.TextField(help_text="Encrypted Mylar3 API key")),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mylar_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mylar3 instance",
                "verbose_name_plural": "Mylar3 instances",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "base_url"),
                        name="integrations_mylarinstance_unique_user_base_url",
                    )
                ],
            },
        ),
    ]
