# Generated by Django 5.2.16 on 2026-09-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0048_mylarinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="plexaccount",
            name="mark_watched_checkpoint",
            field=models.DateTimeField(
                blank=True,
                help_text="Newest Plex history viewedAt already polled",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plexaccount",
            name="mark_watched_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether recurring Plex history polling for manually marked watched items is enabled",
            ),
        ),
    ]
