# Generated by Django 5.2.16 on 2026-09-26 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Squashes the MAL sync branch's development migrations. A database that
    # applied all of them records this one as applied without running it.
    replaces = [
        ('integrations', '0037_malaccount'),
        ('integrations', '0048_merge_0037_malaccount_0047_merge_20260910_1141'),
        ('integrations', '0049_malaccount_full_sync_state'),
        ('integrations', '0050_malaccount_sync_filters'),
        ('integrations', '0051_malaccount_per_item_sync_enabled'),
        ('integrations', '0052_malaccount_split_sync_filters'),
        ('integrations', '0053_malaccount_pull_ratings_enabled'),
        ('integrations', '0054_merge_20260925_2341'),
    ]

    dependencies = [
        ('integrations', '0049_plexaccount_mark_watched_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MALAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_username', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('sync_enabled', models.BooleanField(default=True)),
                ('connection_broken', models.BooleanField(default=False, help_text='True once MyAnimeList rejects the refresh token, until reconnected')),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('per_item_sync_enabled', models.BooleanField(default=True, help_text='Push status/progress/score to MyAnimeList as each entry is edited')),
                ('sync_filter_completed', models.BooleanField(default=True, help_text='Include Completed entries in a full sync to MyAnimeList')),
                ('sync_filter_in_progress', models.BooleanField(default=True, help_text='Include In Progress entries in a full sync to MyAnimeList')),
                ('sync_filter_dropped', models.BooleanField(default=True, help_text='Include Dropped entries in a full sync to MyAnimeList')),
                ('sync_filter_rated_only', models.BooleanField(default=False, help_text='Only include entries that have a score set in a full sync to MyAnimeList')),
                ('sync_ratings_enabled', models.BooleanField(default=True, help_text='Include the score/rating when pushing status to MyAnimeList')),
                ('pull_higher_progress_enabled', models.BooleanField(default=True, help_text="Adopt MyAnimeList's progress locally when it's ahead of Floppy's own record")),
                ('pull_ratings_enabled', models.BooleanField(default=True, help_text="Adopt a MyAnimeList rating locally when Floppy doesn't have one recorded")),
                ('full_sync_status', models.CharField(choices=[('idle', 'Not started'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('full_sync_total', models.PositiveIntegerField(default=0)),
                ('full_sync_processed', models.PositiveIntegerField(default=0)),
                ('full_sync_succeeded', models.PositiveIntegerField(default=0)),
                ('full_sync_failed', models.PositiveIntegerField(default=0)),
                ('full_sync_results', models.JSONField(blank=True, default=list)),
                ('full_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('full_sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mal_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyAnimeList account',
            },
        ),
    ]
