# Generated by Django 5.2.16 on 2026-09-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    # Its number before the squash; a database that ran it records this one.
    replaces = [
        ('integrations', '0055_malaccount_planning_paused_filters'),
    ]

    dependencies = [
        ('integrations', '0050_malaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='malaccount',
            name='sync_filter_paused',
            field=models.BooleanField(default=False, help_text='Include Paused entries in a full sync to MyAnimeList'),
        ),
        migrations.AddField(
            model_name='malaccount',
            name='sync_filter_planning',
            field=models.BooleanField(default=False, help_text='Include Planning entries in a full sync to MyAnimeList'),
        ),
    ]
