# Generated by Django 5.2.16 on 2026-10-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0051_komgaaccount_komgabooklink'),
        ('integrations', '0051_malaccount_planning_paused_filters'),
    ]

    operations = [
    ]
