# FORK: endpoint cases for fork-only routes, appended to endpoints.py's
# get_endpoint_cases() with a single line to keep the upstream file mergeable.
from .endpoints import EndpointCase


def get_fork_endpoint_cases() -> list[EndpointCase]:
    """Return endpoint cases for every fork-only route and method."""
    return [
        EndpointCase(
            "post",
            "api_media_progress",
            args=("movie", "tmdb", 1),
            payload={"operation": "increase"},
        ),
        EndpointCase(
            "post",
            "api_media_season_progress",
            args=("tv", "tmdb", 1, 1),
            payload={"operation": "increase"},
        ),
        EndpointCase("get", "api_collection"),
        EndpointCase("post", "api_collection", payload={}),
        EndpointCase("get", "api_collection_entry", args=(1,)),
        EndpointCase("patch", "api_collection_entry", args=(1,), payload={}),
        EndpointCase("delete", "api_collection_entry", args=(1,)),
        EndpointCase("get", "api_task_status", args=("some-task-id",)),
        EndpointCase("get", "api_music_artists"),
        EndpointCase("post", "api_music_artists", payload={"artist_id": 1}),
        EndpointCase("get", "api_music_artist_detail", args=(1,)),
        EndpointCase("patch", "api_music_artist_detail", args=(1,), payload={}),
        EndpointCase("delete", "api_music_artist_detail", args=(1,)),
        EndpointCase("post", "api_music_artist_sync", args=(1,), payload={}),
        EndpointCase("delete", "api_music_artist_plays", args=(1,)),
        EndpointCase("get", "api_music_albums"),
        EndpointCase("post", "api_music_albums", payload={"album_id": 1}),
        EndpointCase("get", "api_music_album_detail", args=(1,)),
        EndpointCase("patch", "api_music_album_detail", args=(1,), payload={}),
        EndpointCase("delete", "api_music_album_detail", args=(1,)),
        EndpointCase("get", "api_music_album_tracks", args=(1,)),
        EndpointCase("delete", "api_music_album_plays", args=(1,)),
        EndpointCase("post", "api_music_song_play", payload={"album_id": 1}),
        EndpointCase(
            "patch",
            "api_music_track_score",
            args=(1,),
            payload={"score": 8},
        ),
        EndpointCase("post", "api_music_bulk_plays", payload={}),
        EndpointCase("get", "api_podcast_shows"),
        EndpointCase("post", "api_podcast_shows", payload={"show_id": 1}),
        EndpointCase("get", "api_podcast_show_detail", args=(1,)),
        EndpointCase("patch", "api_podcast_show_detail", args=(1,), payload={}),
        EndpointCase("delete", "api_podcast_show_detail", args=(1,)),
        EndpointCase("get", "api_podcast_show_episodes", args=(1,)),
        EndpointCase("post", "api_podcast_mark_all_played", args=(1,), payload={}),
        EndpointCase("post", "api_podcast_episode_play", payload={"show_id": 1}),
        EndpointCase("get", "api_list_smart_rules", args=(1,)),
        EndpointCase("put", "api_list_smart_rules", args=(1,), payload={}),
        EndpointCase("post", "api_list_smart_sync", args=(1,), payload={}),
        EndpointCase("get", "api_list_collaborators", args=(1,)),
        EndpointCase(
            "put",
            "api_list_collaborators",
            args=(1,),
            payload={"usernames": []},
        ),
        EndpointCase(
            "post",
            "api_list_items_reorder",
            args=(1,),
            payload={"item_id": 1, "action": "first"},
        ),
        EndpointCase(
            "put",
            "api_list_items_order",
            args=(1,),
            payload={"item_ids": [1]},
        ),
        EndpointCase("get", "api_list_recommendations", args=(1,)),
        EndpointCase("post", "api_list_recommendations", args=(1,), payload={}),
        EndpointCase(
            "post",
            "api_list_recommendation_decision",
            args=(1, 1, "approve"),
            payload={},
        ),
        EndpointCase("get", "api_list_activity", args=(1,)),
        EndpointCase("get", "api_collection_status", args=(1,)),
        EndpointCase("delete", "api_collection_season", args=(1,)),
        EndpointCase("get", "api_discover"),
        EndpointCase("post", "api_discover_refresh", payload={}),
        EndpointCase("get", "api_discover_hidden"),
        EndpointCase(
            "post",
            "api_discover_hidden",
            payload={"item_id": 1, "action": "hide"},
        ),
        EndpointCase("get", "api_home"),
        EndpointCase("get", "api_user_preferences"),
        EndpointCase("patch", "api_user_preferences", payload={}),
        EndpointCase("get", "api_user_sidebar"),
        EndpointCase("put", "api_user_sidebar", payload={"media_types": {}}),
        EndpointCase("get", "api_user_notifications"),
        EndpointCase("patch", "api_user_notifications", payload={}),
        EndpointCase("get", "api_user_notification_exclusions"),
        EndpointCase(
            "post",
            "api_user_notification_exclusions",
            payload={"item_id": 1},
        ),
        EndpointCase(
            "delete",
            "api_user_notification_exclusions",
            payload={"item_id": 1},
        ),
        EndpointCase("post", "api_user_notification_test", payload={}),
        EndpointCase("post", "api_user_token_regenerate", payload={}),
        EndpointCase("get", "api_imports_activity"),
        EndpointCase("post", "api_import_dispatch", args=("mal",), payload={}),
        EndpointCase("get", "api_export_csv"),
        EndpointCase("get", "api_export_template"),
        EndpointCase("get", "api_playback_progress"),
        EndpointCase(
            "put",
            "api_playback_progress",
            payload={
                "media_type": "movie",
                "ids": {"tmdb": "603"},
                "position_seconds": 60,
            },
        ),
        EndpointCase(
            "delete",
            "api_playback_progress",
            payload={"media_type": "movie", "ids": {"tmdb": "603"}},
        ),
        EndpointCase("get", "api_statistics_overview"),
        EndpointCase(
            "post",
            "api_statistics_refresh",
            payload={"range_name": "Last 12 Months"},
        ),
        EndpointCase(
            "post",
            "api_media_episode_watch",
            args=("tv", "tmdb", 1, 1, 1),
            payload={},
        ),
        EndpointCase(
            "delete",
            "api_media_episode_watch",
            args=("tv", "tmdb", 1, 1, 1),
        ),
        EndpointCase(
            "post",
            "api_media_episode_drop",
            args=("tv", "tmdb", 1, 1, 1),
            payload={},
        ),
        EndpointCase(
            "post",
            "api_media_episode_bulk",
            args=("tv", "tmdb", 1),
            payload={},
        ),
        EndpointCase("get", "api_media_tags", args=("movie", "tmdb", 1)),
        EndpointCase(
            "put",
            "api_media_tags",
            args=("movie", "tmdb", 1),
            payload={"tag_ids": []},
        ),
        EndpointCase(
            "patch",
            "api_media_episode_score",
            args=("tv", "tmdb", 1, 1, 1),
            payload={"score": 8},
        ),
        EndpointCase(
            "get",
            "api_media_provider_preference",
            args=("movie", "tmdb", 1),
        ),
        EndpointCase(
            "put",
            "api_media_provider_preference",
            args=("movie", "tmdb", 1),
            payload={"provider": "tmdb"},
        ),
        EndpointCase(
            "patch",
            "api_item_image",
            args=(1,),
            payload={"image_url": "https://example.com/x.jpg"},
        ),
        EndpointCase("patch", "api_item_metadata", args=(1,), payload={}),
        EndpointCase("get", "api_history"),
        EndpointCase("delete", "api_history_record", args=("movie", "1")),
        EndpointCase("get", "api_tags"),
        EndpointCase("post", "api_tags", payload={"name": "tag"}),
        EndpointCase("patch", "api_tag_detail", args=(1,), payload={"name": "t"}),
        EndpointCase("delete", "api_tag_detail", args=(1,)),
    ]
