# Generated by Django 5.2.2 on 2026-03-02 16:38

from django.db import migrations, models


# FORK: drift-resilient constraint op per fork migration convention
# (see app/migrations/0053_add_boardgame.py); upstream uses a raw
# AddConstraint here.
def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def populate_list_item_id(apps, schema_editor):
    """Populate list_item_id for existing custom list items ordered by date_added.

    Batches writes with bulk_update instead of one save() per row: on large
    tables the per-row version does thousands of serial round trips with no
    progress output, which can exceed the entrypoint's migrate timeout and
    look like a hang (issue #341).
    """
    CustomListItem = apps.get_model('lists', 'CustomListItem')
    BATCH_SIZE = 1000

    items = CustomListItem.objects.order_by(
        'custom_list_id',
        'date_added',
        'id',
    ).iterator(chunk_size=BATCH_SIZE)

    batch = []
    current_list_id = object()
    index = 0
    processed = 0

    for item in items:
        if item.custom_list_id != current_list_id:
            current_list_id = item.custom_list_id
            index = 0
        item.list_item_id = index
        index += 1
        batch.append(item)
        processed += 1

        if len(batch) >= BATCH_SIZE:
            CustomListItem.objects.bulk_update(batch, ['list_item_id'], batch_size=BATCH_SIZE)
            batch = []
            print(f"  populate_list_item_id: {processed} items processed", flush=True)

    if batch:
        CustomListItem.objects.bulk_update(batch, ['list_item_id'], batch_size=BATCH_SIZE)

    print(f"  populate_list_item_id: {processed} items processed (done)", flush=True)


def reverse_populate_list_item_id(apps, schema_editor):
    """Reverse backfill by resetting list_item_id to null."""
    CustomListItem = apps.get_model('lists', 'CustomListItem')
    CustomListItem.objects.update(list_item_id=None)


class Migration(migrations.Migration):

    # The backfill can queue deferred PostgreSQL FK trigger events. Commit it
    # before adding the unique constraint, otherwise PostgreSQL rejects the
    # ALTER TABLE with "cannot ALTER TABLE ... because it has pending trigger
    # events" (issue #352).
    atomic = False

    dependencies = [
        ('app', '0051_migrate_simkl_periodoc_tasks'),
        ('lists', '0003_alter_customlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlistitem',
            name='list_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=populate_list_item_id,
            reverse_code=reverse_populate_list_item_id,
        ),
        AddConstraintIfNotExists(
            model_name='customlistitem',
            constraint=models.UniqueConstraint(fields=('custom_list', 'list_item_id'), name='lists_customlistitem_unique_list_item_id'),
        ),
    ]
