# Generated by Django 5.2.9 on 2026-07-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0009_add_customlist_public_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customlist",
            name="source",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("trakt", "Trakt"),
                    ("mdblist", "MDBList"),
                ],
                default="local",
                max_length=20,
            ),
        ),
    ]
