# Generated by Django 5.2.9 on 2026-07-15 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0004_customlistitem_list_item_id_and_more"),
        ("lists", "0010_alter_customlist_source"),
    ]

    operations = []
