# Generated by Django 5.2.16 on 2026-08-09 22:00

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0149_merge_20260806_1556"),
        ("lists", "0011_merge_20260715_0747"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customlistitem",
            name="lists_customlistitem_unique_list_item_id",
        ),
        migrations.AddConstraint(
            model_name="customlistitem",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("custom_list", "list_item_id"),
                name="lists_customlistitem_unique_list_item_id",
            ),
        ),
    ]
