# Generated by Django 5.2.16 on 2026-08-13 21:58

from django.conf import settings
from django.db import migrations, models


def _constraint_exists(schema_editor, constraint_name):
    """Return whether PostgreSQL already has the named constraint."""
    if schema_editor.connection.vendor != "postgresql":
        return False
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if not _constraint_exists(schema_editor, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it does not exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if _constraint_exists(schema_editor, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_hardcover_edition_preference'),
        ('lists', '0012_defer_customlistitem_list_item_id_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="customlistitem",
            name="lists_customlistitem_unique_list_item_id",
        ),
        AddConstraintIfNotExists(
            model_name="customlistitem",
            constraint=models.UniqueConstraint(
                fields=("custom_list", "list_item_id"),
                name="lists_customlistitem_unique_list_item_id",
            ),
        ),
    ]
