# Generated by Django 5.2.16 on 2026-09-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0014_customlist_include_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customlist",
            name="source",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("trakt", "Trakt"),
                    ("mdblist", "MDBList"),
                    ("wetrakr", "WeTrakr"),
                ],
                default="local",
                max_length=20,
            ),
        ),
    ]
