# Generated by Django 5.2.9 on 2026-07-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0103_user_stats_split_tv_anime"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_screen_media_type_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="User's preferred order of media-type sections on the Home screen",
            ),
        ),
    ]
