# Generated by Django 5.2.9 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0106_user_studio_sort_by_user_studio_sort_by_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sidebar_media_type_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="User's preferred order of media types in the sidebar",
            ),
        ),
    ]
