# Generated by Django 5.2.16 on 2026-07-31 17:51

from django.db import migrations, models


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0109_user_jellyfin_mark_played_enabled_and_more"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="user",
            name="tv_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="season_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="movie_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="anime_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="manga_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="game_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="book_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="boardgame_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="music_status_valid",
        ),
        RemoveConstraintIfExists(
            model_name="user",
            name="podcast_status_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="anime_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="boardgame_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="book_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comic_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="game_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="manga_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="movie_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="music_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="podcast_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="season_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tv_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
    ]
