# Generated by Django 5.2.16 on 2026-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0110_remove_user_tv_status_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tmdb_proxy_url",
            field=models.TextField(
                blank=True,
                help_text="Encrypted outbound proxy URL for TMDB requests (e.g. socks5://user:pass@host:port)",
            ),
        ),
    ]
