# Generated by Django 5.2.16 on 2026-08-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0142_historicalpodcast_position_updated_at_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0111_user_tmdb_proxy_url"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_sort",
            field=models.CharField(
                choices=[
                    ("date_added", "Date Added"),
                    ("custom", "Custom"),
                    ("title", "Title"),
                    ("media_type", "Media Type"),
                    ("rating", "Rating"),
                    ("progress", "Progress"),
                    ("status", "Status"),
                    ("release_date", "Release Date"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                ],
                default="date_added",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planning", "Planning"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=128,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "list_detail_sort__in",
                        [
                            "date_added",
                            "custom",
                            "title",
                            "media_type",
                            "rating",
                            "progress",
                            "status",
                            "release_date",
                            "start_date",
                            "end_date",
                        ],
                    )
                ),
                name="list_detail_sort_valid",
            ),
        ),
    ]
