# Generated by Django 5.2.16 on 2026-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0142_historicalpodcast_position_updated_at_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0112_remove_user_list_detail_status_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_sort_valid",
        ),
        migrations.AddField(
            model_name="user",
            name="list_detail_layout",
            field=models.CharField(
                choices=[("grid", "Grid"), ("table", "Table")],
                default="grid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_sort",
            field=models.CharField(
                choices=[
                    ("date_added", "Date Added"),
                    ("custom", "Custom"),
                    ("title", "Title"),
                    ("media_type", "Media Type"),
                    ("rating", "Rating"),
                    ("progress", "Progress"),
                    ("status", "Status"),
                    ("release_date", "Release Date"),
                    ("start_date", "Start Date"),
                    ("end_date", "End Date"),
                    ("platform", "Platform"),
                ],
                default="date_added",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "list_detail_sort__in",
                        [
                            "date_added",
                            "custom",
                            "title",
                            "media_type",
                            "rating",
                            "progress",
                            "status",
                            "release_date",
                            "start_date",
                            "end_date",
                            "platform",
                        ],
                    )
                ),
                name="list_detail_sort_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("list_detail_layout__in", ["grid", "table"])),
                name="list_detail_layout_valid",
            ),
        ),
    ]
