# Generated by Django 5.2.16 on 2026-08-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0113_remove_user_list_detail_sort_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="premiere_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Receive a weekly digest of new show and season premieres",
            ),
        ),
    ]
