# Generated by Django 5.2.16 on 2026-08-05 00:31

from django.db import migrations, models


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when a database constraint already exists."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return False
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        if not _constraint_exists(schema_editor, from_model._meta.db_table, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(schema_editor, to_model._meta.db_table, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0145_alter_metadatabackfillstate_field"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0115_user_theme"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="user",
            name="home_sort_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="home_sort",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("recent", "Recent"),
                    ("completion", "Completion"),
                    ("episodes_left", "Episodes Left"),
                    ("title", "Title"),
                    ("random", "Random"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
        AddConstraintIfNotExists(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "home_sort__in",
                        [
                            "upcoming",
                            "recent",
                            "completion",
                            "episodes_left",
                            "title",
                            "random",
                        ],
                    )
                ),
                name="home_sort_valid",
            ),
        ),
    ]
