# Generated by Django 5.2.16 on 2026-08-10 03:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0115_user_metadata_language"),
        ("users", "0116_remove_user_home_sort_valid_and_more"),
    ]

    operations = []
