# Generated by Django 5.2.16 on 2026-08-11 14:25

from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def backfill_existing_users_as_onboarded(apps, schema_editor):
    """Mark every user that already exists as having completed onboarding.

    Runs once, at migration time, against the rows that exist right now —
    it never touches users created afterwards, who get the model's
    "not_started" default and go through the setup wizard normally.
    """
    User = apps.get_model("users", "User")
    User.objects.update(onboarding_status="completed", onboarding_step="done")


def noop_reverse(apps, schema_editor):
    """No-op reverse: reverting the schema change doesn't need to undo data."""


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0117_merge_20260810_0306"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="user",
            name="onboarding_selected_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Source slugs chosen to connect during the setup wizard.",
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="onboarding_skipped_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Source slugs explicitly skipped during the setup wizard.",
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                help_text="Progress state for the first-run setup wizard.",
                max_length=20,
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("media_types", "Choose Media Types"),
                    ("services", "Choose Services"),
                    ("services_summary", "Review Services"),
                    ("service_setup", "Connect Services"),
                    ("import_status", "Import Status"),
                    ("done", "Done"),
                ],
                default="media_types",
                help_text="Step to resume the first-run setup wizard on.",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_existing_users_as_onboarded, noop_reverse
        ),
    ]
