# Generated by Django 5.2.16 on 2026-08-14 22:04

from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0122_add_show_each_play"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="user",
            name="logo_style",
            field=models.CharField(
                choices=[("colorful", "Colorful"), ("monochrome", "Monochrome")],
                default="colorful",
                help_text="Preferred Floppy logo style",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default"),
                    ("iso_8601", "ISO 8601"),
                    ("month_d_yyyy", "Month D, YYYY"),
                    ("d_mon_yyyy", "D Mon YYYY"),
                    ("m_d_yyyy", "M/D/YYYY"),
                    ("d_m_yyyy", "D/M/YYYY"),
                    ("dd_mm_yyyy", "DD.MM.YYYY"),
                    ("yyyy_mm_dd", "YYYY/MM/DD"),
                    ("long_eu", "18 Jan, 2026"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("system_default", "System default"),
                    ("h_mm_ampm", "12-hour (h:mm AM/PM)"),
                    ("hh_mm_ampm", "12-hour, leading zero (hh:mm AM/PM)"),
                    ("hh_mm", "24-hour (HH:mm)"),
                    ("hh_mm_ss", "24-hour with seconds (HH:mm:ss)"),
                ],
                default="system_default",
                max_length=20,
            ),
        ),
    ]
