# Generated by Django 5.2.16 on 2026-08-15 03:26

import users.models
from django.db import migrations, models


KNOWN_TEST_USERNAMES = frozenset(
    {
        "benchdebug",
        "benchredir",
        "bookdebug",
        "check_preview",
        "codex-measure-user",
        "codex-refresh-debug",
        "codex-smoke-hardcover",
        "codex_debug_locally",
        "codex_profile_user",
        "dbg",
        "dbg2",
        "debug",
        "debug-6bbc767e",
        "debug-book",
        "debug-history",
        "debug2",
        "debug_client_user",
        "debug_user",
        "debug_user_2",
        "facetchcheck",
        "fetchtech",
        "genre_test_84de2e9a",
        "genre_test_user_tmp",
        "pc_empty_list_review",
        "pc_unplayed_review2",
        "probe",
        "probe_user",
        "qmeasure77",
        "redircheck",
        "regtest_user",
        "rss_qa_check",
        "script_user",
        "scrolltest",
        "smoke",
        "tmp_rel_628f86b0",
        "tmp_rel_b522c96b",
        "tmpstats",
        "tmpu",
        "tmpu_9067b3c7",
        "tmpu_f065d665",
        "tmpuser_bg3",
        "tmpuser_bg4",
        "tvdbtest",
        "tvdbtest2",
        "tvdbtest3",
        "tvdbtest4",
        "u",
        "u2",
        "u287c8267",
        "u2bbe7ba7",
        "u3",
        "u4",
        "u421f9ea4",
        "u5",
        "u6",
        "u_87602e05",
        "ubc943d17",
        "user_bg-f6952324",
        "uview",
        "verify_ts_test",
        "wordle-test",
        "x",
        "x2",
        "x_shell_2",
        "x_shell_3",
    }
)


def mark_known_test_accounts(apps, schema_editor):
    """Tag the known QA accounts that predate the explicit flag."""
    user_model = apps.get_model("users", "User")
    test_user_ids = [
        user.pk
        for user in user_model.objects.filter(is_test_account=False)
        .only("pk", "username")
        .iterator()
        if user.username.casefold() in KNOWN_TEST_USERNAMES
    ]
    if test_user_ids:
        user_model.objects.filter(pk__in=test_user_ids).update(is_test_account=True)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0123_user_logo_style_alter_user_date_format_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.FloppyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_test_account",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Exclude this account from normal user pickers and sharing controls.",
            ),
        ),
        migrations.RunPython(mark_known_test_accounts, migrations.RunPython.noop),
    ]
