# Generated by Django 5.2.16 on 2026-09-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_remove_user_hardcover_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ui_language',
            field=models.CharField(choices=[('auto', 'Auto (browser language)'), ('en', 'English'), ('de', 'Deutsch'), ('es', 'Español')], default='auto', help_text='Preferred UI display language', max_length=10),
        ),
    ]
