# Generated by Django 5.2.16 on 2026-09-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_alter_user_ui_language'),
        ('users', '0133_user_book_metadata_source_default_and_more'),
        ('users', '0134_user_playback_webhook_secret'),
    ]

    operations = [
    ]
