# Generated by Django 5.2.16 on 2026-09-25 12:28

from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_merge_20260918_0021'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_api_key',
            field=models.TextField(blank=True, default='', help_text='Encrypted Seerr API key'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_url',
            field=models.URLField(blank=True, help_text='Seerr server URL, used to request movies and shows from Floppy'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_user_id',
            field=models.PositiveIntegerField(blank=True, help_text='Seerr user id resolved from seerr_username when settings are saved', null=True),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='seerr_username',
            field=models.CharField(blank=True, default='', help_text='Seerr login (username or email) the requests are made as', max_length=255),
        ),
    ]
