# Generated by Django 5.2.16 on 2026-09-20 16:16

from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def _constraint_exists(schema_editor, constraint_name):
    """Return whether PostgreSQL already has the named constraint."""
    if schema_editor.connection.vendor != "postgresql":
        return False
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [constraint_name],
        )
        return cursor.fetchone() is not None


class RemoveConstraintIfExists(migrations.RemoveConstraint):
    """Remove a constraint only when it exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if not _constraint_exists(schema_editor, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it does not exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if _constraint_exists(schema_editor, self.constraint.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0014_customlist_include_notes'),
        ('users', '0135_merge_20260918_0021'),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name='homescreenrow',
            name='home_screen_row_media_type_valid',
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='home_media_type_chip_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Custom hexadecimal label colors keyed by media type'),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='home_media_type_chip_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('soft', 'Soft'), ('outline', 'Outline')], default='soft', help_text='Appearance of media-type labels on mixed Home rows', max_length=12),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='home_media_type_chips_enabled',
            field=models.BooleanField(default=True, help_text='Show media-type labels on mixed in-progress and finished Home rows'),
        ),
        migrations.AlterField(
            model_name='homescreenrow',
            name='media_type',
            field=models.CharField(choices=[('all', 'All media'), ('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('comicissue', 'Comic Issue'), ('boardgame', 'Board Game'), ('music', 'Music'), ('podcast', 'Podcast')], max_length=16),
        ),
        AddConstraintIfNotExists(
            model_name='homescreenrow',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['all', 'tv', 'season', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'comicissue', 'boardgame', 'music', 'podcast'])), name='home_screen_row_media_type_valid'),
        ),
    ]
