# Generated by Django 5.2.16 on 2026-09-19 17:41

from django.db import migrations, models


def column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        columns = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    return any(column.name == column_name for column in columns)


class AddFieldIfNotExists(migrations.AddField):
    """Preserve state while tolerating columns already present in a fork."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        if column_exists(schema_editor, model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_merge_20260918_0021'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='user',
            name='logo_text_color_end',
            field=models.CharField(default='#2563eb', help_text='Custom wordmark gradient end', max_length=7),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='logo_text_color_start',
            field=models.CharField(default='#1f2937', help_text='Custom wordmark color or gradient start', max_length=7),
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='logo_text_fill',
            field=models.CharField(choices=[('theme_solid', 'Theme color'), ('custom_solid', 'Custom color'), ('theme_gradient', 'Theme gradient'), ('custom_gradient', 'Custom gradient')], default='theme_gradient', help_text='Color treatment used by the navigation wordmark', max_length=16),
        ),
    ]
