# Generated by Django 5.2.16 on 2026-09-25 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0135_merge_20260918_0021"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "TV Show"),
                            ("season", "TV Season"),
                            ("episode", "Episode"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("game", "Game"),
                            ("book", "Book"),
                            ("comic", "Comic"),
                            ("comicissue", "Comic Issue"),
                            ("boardgame", "Board Game"),
                            ("music", "Music"),
                            ("podcast", "Podcast"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("query", models.TextField(blank=True, default="")),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["media_type", "position", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "media_type", "position"],
                        name="users_saved_user_id_2d992d_idx",
                    )
                ],
            },
        ),
    ]
