# Generated by Django 5.2.16 on 2026-10-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0137_add_gcd_source'),
        ('users', '0137_user_group_scrobbled_anime'),
    ]

    operations = [
    ]
