# Generated by Django 5.2.16 on 2026-09-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0143_tile_metadata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='media_card_subtitle_display_valid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hide_zero_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='media_card_subtitle_display',
        ),
        migrations.RemoveField(
            model_name='user',
            name='progress_bar',
        ),
    ]
